app:
  buffsize: 100
  reader:
    kafka:
      brokersAddr:
        - "127.0.0.1:9092"
      topic: "testlog"
  writer:
    stdout: true
    file:
      filePath: "app_log"
      fileName: "app"
      maxSize: 0
      rotateByTime: true